version: '3.9'

# Define services
services:

  # Database (Mysql)
  ad-mysqldb:
    image: mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=GetFitWithHenry
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - ad-network-backend

  # Springboot Java backend
  ad-backend:
    image: gavingyh/ad_backend:latest
    ports:
      - 8080:8080
    depends_on:
      - ad-mysqldb
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.mvc.format.date":"dd-MM-yyyy",
        "spring.datasource.url":"jdbc:mysql://ad-mysqldb:3306/GetFitWithHenry?autoReconnect=true&useSSL=false&serverTimezone=GMT&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username":"root",
        "spring.datasource.password":"password",  
        "spring.thymeleaf.mode":"HTML",
        "spring.session.store-type":"none",
        "spring.session.jdbc.initialize-schema":"always",
        "spring.jpa.hibernate.ddl-auto":"update",
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.properties.hibernate.globally_quoted_identifiers":"true",
        "spring.jpa.defer-datasource-initialization":"true"
        }'  
    networks:
      - ad-network-frontend
      - ad-network-backend   
  

  # React.js Recipe
  ad-react-recipe:
    image: gavingyh/ad_react_recipe:latest
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - ad-backend
    volumes:
      - ./frontend/node_modules:/usr/app/node_modules
      - ./frontend:/usr/app
    networks:
      - ad-network-frontend
    
  # React.js Admin
  ad-react-admin:
    image: gavingyh/ad_react_admin:latest
    ports:
      - 3001:3001
    restart: unless-stopped
    depends_on:
      - ad-backend
    volumes:
      - ./frontend/node_modules:/usr/app/node_modules
      - ./frontend:/usr/app
    networks:
      - ad-network-frontend
   
  # Flask ML api
  ad-ml-model:
    image: gavingyh/ad_ml_model:latest
    ports:
      - 5000:5000
    depends_on:
      - ad-backend
    networks:
      - ad-network-backend
    
      
# Volumes
volumes:
  db-data:

# Networks
networks:
  ad-network-frontend:
  ad-network-backend:
  