name: myenv
 
dependencies:
    - python
    - pip>=19.0
    - scikit-learn==1.0.2
    - pandas==1.4.2
    - requests==2.27.1
    - pyyaml
    - flask==2.1.3
    - tensorflow
    - selenium
    - pip:
        - matplotlib==3.5.2
        - pillow==9.1.0
        - webdriver_manager
        